# Generated by Django 5.2.11 on 2026-03-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnerjiHesaplayiciAyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncel_kwh_fiyati', models.DecimalField(decimal_places=2, default=2.5, help_text='Hesaplama aracında kullanılacak güncel 1 kWh elektrik fiyatını girin.', max_digits=6, verbose_name='Güncel Elektrik Birim Fiyatı (TL/kWh)')),
                ('ortalama_tasarruf_orani', models.IntegerField(default=60, help_text='Zafer Tech sistemlerinin eski sistemlere göre sağladığı ortalama % tasarruf.', verbose_name='Ortalama LED Tasarruf Oranı (%)')),
            ],
            options={
                'verbose_name': 'Hesaplayıcı Ayarı',
                'verbose_name_plural': 'Hesaplayıcı Ayarları',
            },
        ),
    ]
