# Generated by Django 5.2.11 on 2026-03-02 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(help_text='URL ve filtreleme için benzersiz isim (Örn: endustriyel)', unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Proje Adı (Örn: Doğuş Oto Kartal)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Kısa Açıklama')),
                ('gorsel_url', models.URLField(blank=True, help_text='Geçici test için görsel linki')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeler', to='core.kategori')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
            },
        ),
    ]
