# Generated by Django 5.2.11 on 2026-03-02 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kategori_proje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='ilerleme_yuzdesi',
            field=models.IntegerField(default=0, help_text='0 ile 100 arası bir değer girin.', verbose_name='İlerleme Durumu (%)'),
        ),
        migrations.AddField(
            model_name='proje',
            name='musteri',
            field=models.ForeignKey(blank=True, help_text='Bu projeyi hangi müşteri kendi panelinde görecek?', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atanan Müşteri'),
        ),
        migrations.AddField(
            model_name='proje',
            name='son_durum_notu',
            field=models.CharField(blank=True, help_text='Örn: Kablo altyapısı tamamlandı, pano montajına geçiliyor.', max_length=255, verbose_name='Son Durum Notu'),
        ),
    ]
