# Generated by Django 5.2.11 on 2026-03-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proje_ilerleme_yuzdesi_proje_musteri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='santiye_fotografi',
            field=models.ImageField(blank=True, help_text='Müşterinin portalda göreceği güncel şantiye/proje fotoğrafı.', null=True, upload_to='santiye_fotograflari/', verbose_name='Son Durum Fotoğrafı'),
        ),
    ]
