# Generated by Django 5.2.11 on 2026-03-03 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_proje_santiye_fotografi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjeGorseli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorsel', models.ImageField(upload_to='proje_galerisi/', verbose_name='Fotoğraf')),
                ('sira', models.IntegerField(default=0, help_text='Küçük sayı önce gösterilir.', verbose_name='Gösterim Sırası')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='core.proje', verbose_name='Ait Olduğu Proje')),
            ],
            options={
                'verbose_name': 'Proje Görseli',
                'verbose_name_plural': 'Proje Görselleri',
                'ordering': ['sira'],
            },
        ),
    ]
