# Generated by Django 5.2.11 on 2026-03-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projegorseli'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogYazisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('ozet', models.TextField(help_text='Blog listesinde görünecek kısa açıklama.', verbose_name='Kısa Özet')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='blog_gorselleri/', verbose_name='Kapak Görseli')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('yayinda_mi', models.BooleanField(default=True, help_text='Taslak olarak kaydetmek isterseniz işareti kaldırın.', verbose_name='Yayında mı?')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
