# Generated by Django 5.2.11 on 2026-03-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogyazisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proje',
            name='gorsel_url',
        ),
        migrations.AddField(
            model_name='proje',
            name='kapak_fotografi',
            field=models.ImageField(blank=True, help_text='Proje kartlarında görünecek ana fotoğraf.', null=True, upload_to='proje_kapaklari/', verbose_name='Kapak Fotoğrafı'),
        ),
    ]
