# Generated by Django 5.2.11 on 2026-05-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_proje_gorsel_url_proje_kapak_fotografi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proje',
            options={'ordering': ['sira', '-id'], 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AddField(
            model_name='proje',
            name='sira',
            field=models.IntegerField(default=0, help_text='Küçük sayı en üstte/önce gösterilir (Örn: 1 en üstte).', verbose_name='Gösterim Sırası'),
        ),
    ]
