# Generated by Django 5.2.11 on 2026-05-02 09:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_proje_options_proje_sira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogyazisi',
            name='icerik',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='İçerik'),
        ),
    ]
